:global:
  feature_componentCompile: true
  feature_goUnitTests: false
  feature_goldenTests: false
  feature_kubevalValidate: false
  componentName: ""

.github/ISSUE_TEMPLATE/config.yml:
  contact_links:
    - name: ‚ùì Help and Support RocketChat Channel
      url: https://community.appuio.ch
      about: Please ask and answer questions here. üè•

.github/workflows/test.yaml:
  makeTarget: test
  matrix: {}
  # key: provider
  # entries:
  #   - variant1
  #   - variant2

docs/antora.yml:
  version: master

LICENSE:
  year: 2021
  holder: VSHN AG <info@vshn.ch>

.gitignore:
  # Add additional lines to the `.gitignore` file
  additionalEntries: []

Makefile:
  # Add additional Makefiles
  includes: []

CHANGELOG.md:
  delete: true
